[package]
name = "matchlab-ranking"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
matchlab-core = { path = "../matchlab-core" }
matchlab-lua = { path = "../matchlab-lua" }
serde.workspace = true
serde_yaml.workspace = true
mlua = { workspace = true, features = ["send"] }

[dev-dependencies]
serde_yaml.workspace = true
